---
kind: pipeline
name: default

steps:
  - name: echo
    commands:
      - ls -al
      - echo haha
      - echo test
  when:
    event:
      - push

trigger:
  branch:
    - master
  event:
    - push
