---
kind: pipeline
type: docker
name: default

steps:
  - name: echo
    image: node:8.11.3-alpine
    commands:
      - ls -al
      - echo haha
      - echo test
      - echo test
  when:
    event:
      - push

trigger:
  branch:
    - master
  event:
    - push
